### ISSUE TITLE
code understanding

### ISSUE THREAD

**Issue by as485** [gholamifrd/vimplugins#1]
Hi there, When I was learning and trying to understand the function "def time_difference(date1, date2)" in vimplugins/.vim/bundle/python-mode/submodules/autopep8/autopep8.py, I was confused about the description of the its delivered function. My understanding of this code snippet is "convert the time to iso 8601 format". Do I understand that right?

**Comment by gholamifrd** [comment]
Hi buddy, I'm sorry this repo is just a collection of other plugins and I just use them as they are, so if you have a question u should ask in the original plugin page [https://github.com/python-mode/python-mode](https://github.com/python-mode/python-mode)

**Comment by as485** [comment]
Thanks for your response very much. I will try as you said.
